query GetCommits {
  repository(owner: "farosFreed", name: "Bricktris") {
    defaultBranchRef {
      target {
        ... on Commit {
          history(first: 1) {
            edges {
              node {
                ... on Commit {
                  committedDate
                }
              }
            }
          }
        }
      }
    }
  }
}
